language: node_js
node_js:
  - '6'
sudo: false
services:
  - mongodb
before_script:
  - mongo admin --eval 'db.createUser({user:"admin",pwd:"admin",roles:[{role:"userAdminAnyDatabase",db:"admin"}]});'
script:
  - grunt
  - grunt coverallsio